version: '3'

networks:
    symfony:

services:
    app:
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - redis
            - mysql
            - mailhog
        networks:
            - symfony

    mysql:
        image: mariadb:10.6
        restart: unless-stopped
        tty: true
        ports:
            - '4306:3306'
        volumes:
            - ./dockerfiles/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: shop
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - symfony

    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - symfony

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - symfony

    composer:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        entrypoint: ['composer']
        networks:
            - symfony

    npm:
        image: node:current-alpine
        volumes:
            - ./:/var/www/html
        ports:
            - '3000:3000'
            - '3001:3001'
            - '5173:5173'
        working_dir: /var/www/html
        networks:
            - symfony

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - symfony
